#!/usr/bin/env python3
"""Generates testing/Manual_Test_Cases.xlsx from the TEST_CASES data below.
Re-run this script after editing test cases here to regenerate the sheet."""

import os
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.datavalidation import DataValidation

OUTPUT_PATH = os.path.join(os.path.dirname(__file__), "Manual_Test_Cases.xlsx")

COLUMNS = [
    "Test Case ID", "Module", "Test Scenario", "Pre-conditions",
    "Test Steps", "Test Data", "Expected Result", "Actual Result",
    "Status", "Priority", "Tested By", "Date Tested", "Remarks",
]

# (module, scenario, preconditions, steps, test_data, expected_result, priority)
TEST_CASES = [
    # ---------------- Login / Authentication ----------------
    ("Login", "Login with valid credentials", "User account exists in the system",
     "1. Go to login page\n2. Enter valid email\n3. Enter valid password\n4. Click Login",
     "Valid email + correct password", "User is authenticated and redirected to the dashboard matching their role", "High"),
    ("Login", "Login with invalid password", "User account exists",
     "1. Go to login page\n2. Enter valid email\n3. Enter wrong password\n4. Click Login",
     "Valid email, wrong password", "Login is rejected with an error message; user stays on login page", "High"),
    ("Login", "Login with unregistered email", "None",
     "1. Go to login page\n2. Enter an email not in the system\n3. Enter any password\n4. Click Login",
     "unknown@test.com / any password", "Error message shown, login denied", "Medium"),
    ("Login", "Login with empty fields", "None",
     "1. Go to login page\n2. Leave email and password blank\n3. Click Login",
     "Empty fields", "Form validation blocks submission with required-field messages", "Medium"),
    ("Login", "Login with SQL/Script injection in fields", "None",
     "1. Go to login page\n2. Enter payload like ' OR 1=1-- in email/password\n3. Click Login",
     "' OR 1=1--", "Login rejected, no data leak or error stack shown to user", "High"),
    ("Login", "Session persists after page refresh", "User is logged in",
     "1. Log in successfully\n2. Refresh the browser page",
     "N/A", "User remains logged in and on the same dashboard route", "Medium"),
    ("Login", "Logout functionality", "User is logged in",
     "1. Click user menu / logout option\n2. Confirm logout",
     "N/A", "User session/token is cleared and user is redirected to login page", "High"),
    ("Login", "Access dashboard route directly without login", "User is logged out",
     "1. Log out or clear browser storage\n2. Manually navigate to /dashboard/patients",
     "URL: /dashboard/patients", "User is redirected to login page, protected route not rendered", "High"),
    ("Login", "Forgot password request with registered email", "Account exists",
     "1. Go to Forgot Password page\n2. Enter registered email\n3. Submit",
     "Registered email", "System accepts request and shows confirmation message", "Medium"),
    ("Login", "Forgot password request with unregistered email", "None",
     "1. Go to Forgot Password page\n2. Enter an email not in system\n3. Submit",
     "unknown@test.com", "Appropriate error/neutral message shown (no account enumeration)", "Low"),

    # ---------------- Admin & Role Management ----------------
    ("Admin Management", "View list of admin/staff users", "Logged in as admin",
     "1. Navigate to Admin page\n2. Observe user list table",
     "N/A", "All registered staff users are listed with name, email, role, contact", "High"),
    ("Admin Management", "Filter/search admin user list", "At least 2+ users exist",
     "1. Go to Admin page\n2. Enter a name/email in search/filter box",
     "Partial name e.g. 'joh'", "List filters to matching users only; clearing filter restores full list", "Medium"),
    ("Admin Management", "Register a new staff user (Register Role)", "Logged in as admin",
     "1. Go to Register Role page\n2. Fill name, email, contact, password, role\n3. Submit",
     "name: Test User, role: billing", "New user created, appears in Admin list, redirected correctly after add", "High"),
    ("Admin Management", "Register new user with duplicate email", "A user with that email already exists",
     "1. Go to Register Role\n2. Enter an already-registered email\n3. Submit",
     "Existing email", "Form shows duplicate-email error; user is not created twice", "High"),
    ("Admin Management", "Register new user with missing required fields", "None",
     "1. Go to Register Role\n2. Leave required fields blank\n3. Submit",
     "Blank fields", "Validation errors shown; submission blocked", "Medium"),
    ("Admin Management", "View user details from the admin list", "At least one user exists",
     "1. Go to Admin page\n2. Click the View (eye) action on a user",
     "N/A", "User Details page opens showing name, email, role, contact, user ID, created/updated dates and the role's effective permissions. User is NOT logged out or sent to the login page", "High"),
    ("Admin Management", "View details of a doctor's linked login account", "A doctor account provisioned via Add Doctor exists",
     "1. Open User Details for a doctor-role user",
     "N/A", "A linked doctor profile chip is shown with a working link through to that doctor's profile", "Medium"),
    ("Admin Management", "Edit admin then save returns to the admin list", "At least one user exists",
     "1. Open Edit Admin for a user\n2. Change a field\n3. Save",
     "Updated contact number", "Success message shown, then redirect to the Admin list (NOT the login page)", "High"),
    ("Admin Management", "Edit existing admin/staff details", "At least one user exists",
     "1. Open Edit Admin for a user\n2. Change name/contact/role\n3. Save",
     "Updated contact number", "Changes are saved and reflected in Admin list", "High"),
    ("Admin Management", "Delete an admin/staff user", "At least one non-self user exists",
     "1. Go to Admin page\n2. Click delete on a user\n3. Confirm deletion",
     "N/A", "User is removed from the list and can no longer log in", "High"),
    ("Admin Management", "Role Management - view roles and permissions", "Logged in as admin",
     "1. Navigate to Role Management page\n2. Review roles and assigned permissions",
     "N/A", "Roles (admin, doctor, patient_manager, billing) and their permissions display correctly", "Medium"),
    ("Admin Management", "Role Management - update permissions for a role", "Logged in as admin",
     "1. Open a role\n2. Tick/untick an action in a module row (e.g. Read - Pharmacy)\n3. Save",
     "billing role: tick Read - Patients", "Permission change is saved to the Role record; unknown permission keys are rejected by the API", "High"),
    ("Admin Management", "Permission change requires affected user to re-login", "A role's permissions were just changed",
     "1. Change a permission on a role\n2. With that role's user still logged in, retry the affected page\n3. Log that user out and back in\n4. Retry the page",
     "Add Read - Patients to billing role", "Change does NOT apply to the already-logged-in session (permissions are carried in the JWT/localStorage from login); after re-login the new permission applies", "High"),
    ("Admin Management", "Allow All covers read/write/edit for a module", "Logged in as admin",
     "1. Open a role\n2. Tick Allow All for a module only\n3. Save\n4. Log in as that role and exercise read + write + edit actions",
     "pharmacy: Allow All only", "All actions in that module are permitted by _allow_all alone; no need to also tick read/write/edit", "Medium"),
    ("Admin Management", "Non-admin cannot access Admin page", "Logged in as non-admin role (e.g. billing)",
     "1. Log in as billing/doctor/patient_manager\n2. Try to navigate to /dashboard/admin",
     "URL: /dashboard/admin", "Access is blocked/redirected; page/menu item not shown", "High"),

    # ---------------- Doctor Management ----------------
    ("Doctor Management", "View list of doctors", "At least one doctor exists",
     "1. Navigate to Doctors page",
     "N/A", "List of doctors displays with name, specialization, contact details", "High"),
    ("Doctor Management", "Add a new doctor with valid details", "Logged in with permission",
     "1. Go to Add Doctor page\n2. Fill in name, specialization, contact, fee, schedule\n3. Submit",
     "name: Dr. Test, fee: 1500", "Doctor is created and appears in Doctor Management list", "High"),
    ("Doctor Management", "Add doctor with missing required fields", "None",
     "1. Go to Add Doctor page\n2. Leave required fields blank\n3. Submit",
     "Blank fields", "Validation prevents submission with clear error messages", "Medium"),
    ("Doctor Management", "Add doctor with invalid contact number format", "None",
     "1. Go to Add Doctor page\n2. Enter letters in contact field\n3. Submit",
     "contact: abc123", "Field validation rejects non-numeric/invalid format", "Low"),
    ("Doctor Management", "View single doctor profile", "Doctor record exists",
     "1. From Doctors list, click on a doctor",
     "N/A", "Doctor View page shows full profile details correctly", "Medium"),
    ("Doctor Management", "Edit doctor details", "Doctor record exists",
     "1. Open Doctor Edit page\n2. Update fee/specialization\n3. Save",
     "Updated fee: 2000", "Changes persist and reflect in Doctor list/profile", "High"),
    ("Doctor Management", "Delete a doctor", "Doctor record exists with no active appointments",
     "1. Go to Doctor Management\n2. Delete a doctor\n3. Confirm",
     "N/A", "Doctor is removed from list; not selectable for new appointments", "Medium"),
    ("Doctor Portal", "Doctor sees today's queue and their upcoming appointments", "Logged in as a doctor with appointments today and later",
     "1. Log in as a doctor\n2. Open My Appointments",
     "N/A", "Two tables: Today (consultation queue) and Upcoming Appointments (after today, soonest first); stat tiles show Today's Total, Completed, Remaining and Upcoming", "High"),
    ("Doctor Portal", "Doctor sees only their own appointments", "Appointments exist for more than one doctor",
     "1. Log in as doctor A\n2. Open My Appointments",
     "N/A", "Only doctor A's appointments are listed; no other doctor's patients appear", "High"),
    ("Doctor Portal", "Today's appointments are not duplicated in Upcoming", "The doctor has appointments today and on later dates",
     "1. Open My Appointments\n2. Compare the two tables",
     "N/A", "No appointment appears in both tables; Upcoming starts from tomorrow so the day's workload is not double counted", "Medium"),
    ("Doctor Portal", "Account with no linked doctor profile", "Logged in as a doctor-role user with no linked Doctor record",
     "1. Open My Appointments",
     "N/A", "A clear message explains no doctor profile is linked and to contact an admin, instead of an empty table", "Medium"),
    ("Doctor Consultation", "Open a consultation from today's queue", "An appointment assigned to the doctor exists for today",
     "1. From My Appointments, click Start Consultation",
     "N/A", "Consultation page loads showing the patient header, clinical fields and the prescription method selector", "High"),
    ("Doctor Consultation", "Patient header shows identifying and clinical context", "Patient record exists",
     "1. Open a consultation\n2. Review the header",
     "N/A", "Shows patient name, patient ID, age, gender, contact, blood group, appointment date/time, service, doctor and appointment status", "High"),
    ("Doctor Consultation", "Known allergies are highlighted", "The patient has allergies recorded at the patient desk",
     "1. Open a consultation for that patient",
     "Allergies: Penicillin", "Allergies appear as a prominent warning callout in the patient header", "High"),
    ("Doctor Consultation", "Save consultation as a draft", "Consultation page open",
     "1. Fill Chief Complaint, Symptoms, Examination, Diagnosis, Notes\n2. Click Save Consultation\n3. Reload the page",
     "Diagnosis: Tension headache", "Clinical fields are persisted and reloaded; the appointment is NOT completed and billing is not advanced", "High"),
    ("Doctor Consultation", "Clinical notes are stored separately from the prescription", "A consultation with notes but no medicines",
     "1. Enter a diagnosis and notes\n2. Choose No Prescription\n3. Complete the consultation",
     "N/A", "The clinical record is saved even though no prescription exists (notes are not lost with no medicines to dispense)", "High"),
    ("Doctor Consultation", "Type Prescription - medicine entry is shown", "Consultation page open, medicines in inventory",
     "1. Select Type Prescription",
     "N/A", "The medicine entry grid is shown with medicine search, quantity, dosage, frequency, duration and instructions", "High"),
    ("Doctor Consultation", "Type Prescription - save and send to pharmacy", "Type Prescription selected",
     "1. Select a medicine and quantity\n2. Click Save Prescription",
     "Paracetamol, qty 10", "Prescription is saved, its items are QUEUED, and it appears in the Pharmacy Dispensing Queue", "High"),
    ("Doctor Consultation", "Type Prescription - complete leaves the visit with pharmacy", "A typed prescription has been saved",
     "1. Click Complete Consultation",
     "N/A", "Appointment becomes Completed; the visit stays with the pharmacy and only becomes collectable in Billing after all items are dispensed", "High"),
    ("Doctor Consultation", "Type Prescription - cannot complete with nothing saved", "Type Prescription selected, no medicines saved",
     "1. Select Type Prescription\n2. Click Complete Consultation without saving any medicine",
     "N/A", "Completion is refused with a message to save the prescription or pick another method; nothing is billed and the appointment stays open", "High"),
    ("Doctor Consultation", "Handwritten - medicine entry is hidden", "Consultation page open",
     "1. Select Handwritten Prescription",
     "N/A", "The medicine grid is hidden and an explanation plus a confirmation checkbox is shown", "High"),
    ("Doctor Consultation", "Handwritten - confirmation is required", "Handwritten Prescription selected, checkbox unticked",
     "1. Select Handwritten Prescription\n2. Click Complete Consultation without ticking the confirmation",
     "N/A", "Completion is refused asking for confirmation that the paper prescription was given; appointment stays open and nothing is billed", "High"),
    ("Doctor Consultation", "Handwritten - complete goes straight to billing", "Handwritten Prescription selected and confirmed",
     "1. Tick the confirmation\n2. Click Complete Consultation",
     "N/A", "Appointment becomes Completed; NO prescription is created; nothing appears in the pharmacy queue; the patient becomes collectable in Billing immediately", "High"),
    ("Doctor Consultation", "Handwritten - reason is recorded for audit", "A consultation was completed as handwritten",
     "1. Inspect the stored consultation record",
     "N/A", "prescriptionMode is stored as HANDWRITTEN with the confirmation timestamp, explaining why no pharmacy prescription exists", "Medium"),
    ("Doctor Consultation", "No Prescription - complete goes straight to billing", "Consultation page open",
     "1. Select No Prescription\n2. Click Complete Consultation",
     "N/A", "A note explains nothing goes to pharmacy; no prescription is created; prescriptionMode NONE stored; patient becomes collectable in Billing immediately", "High"),
    ("Doctor Consultation", "Cannot switch to handwritten after queuing medicines", "A typed prescription has already been saved for this visit",
     "1. Save a typed prescription\n2. Change the method to Handwritten or No Prescription\n3. Complete",
     "N/A", "Completion is refused, because the pharmacy is already holding a prescription for this visit", "High"),
    ("Doctor Consultation", "A completed consultation cannot be completed twice", "A consultation was already completed",
     "1. Reopen the consultation\n2. Attempt to complete it again",
     "N/A", "Refused; the billing transition does not fire a second time and fields are read-only", "Medium"),
    ("Doctor Consultation", "Previous consultations history", "The patient has earlier completed consultations",
     "1. Open a consultation\n2. Review Previous Consultations",
     "N/A", "Lists date, doctor, diagnosis, notes and what was prescribed for each earlier consultation", "Medium"),
    ("Doctor Consultation", "Patient desk records stay separate from consultations", "The patient has both registration vitals and past consultations",
     "1. Open a consultation\n2. Compare Previous Consultations with Patient Registration Records",
     "N/A", "Two clearly separate panels: doctor-authored consultations, and vitals/history recorded at the patient desk", "Medium"),
    ("Doctor Consultation", "Doctor is not exposed to internal billing states", "Consultation page open",
     "1. Review the whole page including after completion",
     "N/A", "No technical statuses (OPEN, PENDING_PHARMACY, READY_FOR_PAYMENT, CLOSED) are shown; only doctor-facing wording", "Medium"),
    ("Doctor Consultation", "SECURITY - prescription cannot be attributed to another doctor", "Logged in as doctor A; doctor B also exists",
     "1. Start a consultation as doctor A\n2. Using browser devtools, alter the saved request to carry doctor B's id/name\n3. Save the prescription",
     "doctorId/doctorName of doctor B", "The stored prescription is attributed to doctor A (identity is derived server-side from the authenticated user; body values are ignored)", "High"),
    ("Doctor Consultation", "SECURITY - consultation cannot be attributed to another doctor", "Logged in as doctor A; doctor B also exists",
     "1. Alter the consultation save request to carry doctor B's id/name\n2. Save",
     "doctorId/doctorName of doctor B", "The consultation is recorded against doctor A, on every save, not just the first", "High"),
    ("Doctor Consultation", "Non-doctor cannot record a consultation", "Logged in as a role without doctor_portal",
     "1. Log in as billing/admin staff\n2. Attempt to save or complete a consultation via the API",
     "N/A", "Request is refused by permission checks server-side, not only hidden in the UI", "High"),
    ("Doctor Management", "Non-doctor cannot access Doctor Portal", "Logged in as non-doctor role",
     "1. Log in as admin/billing/patient_manager\n2. Try to navigate to /dashboard/doctor-home",
     "URL: /dashboard/doctor-home", "Access blocked by ProtectedRoute (requiredPermission doctor_portal)", "High"),

    # ---------------- Patient Management ----------------
    ("Patient Management", "View list of registered patients", "At least one patient exists",
     "1. Navigate to Patients page",
     "N/A", "Patient list displays with name, contact, registration details", "High"),
    ("Patient Management", "Search/filter patients by name or ID", "Multiple patients exist",
     "1. Go to Patients page\n2. Enter search term",
     "Partial patient name", "List filters correctly to matching patients", "Medium"),
    ("Patient Management", "Register a new patient with valid details", "Logged in with manage_patients permission",
     "1. Go to Register Patient page\n2. Fill name, age, gender, contact, address\n3. Submit",
     "name: Test Patient, age: 30", "Patient is created and appears in Patients list", "High"),
    ("Patient Management", "Register patient with missing required fields", "None",
     "1. Go to Register Patient\n2. Leave required fields blank\n3. Submit",
     "Blank fields", "Form validation blocks submission, shows required errors", "Medium"),
    ("Patient Management", "Register patient with invalid contact/NIC format", "None",
     "1. Go to Register Patient\n2. Enter invalid NIC/phone format\n3. Submit",
     "NIC: 123, phone: abcd", "Validation error shown for invalid format", "Low"),
    ("Patient Management", "View patient profile", "Patient record exists",
     "1. From Patients list, click View on a patient",
     "N/A", "View Patient page shows full record: history, appointments, billing summary", "High"),
    ("Patient Management", "Edit patient details", "Patient record exists",
     "1. Open Edit Patient page\n2. Update contact/address\n3. Save",
     "Updated phone number", "Changes are saved and reflected in patient profile", "High"),
    ("Patient Management", "Delete/deactivate a patient record", "Patient record exists",
     "1. From Patients list, delete a patient\n2. Confirm",
     "N/A", "Patient is removed/deactivated; historical records remain intact if applicable", "Medium"),
    ("Patient Management", "Non-permitted role cannot access Patients module", "Logged in as role without manage_patients",
     "1. Log in as a restricted role\n2. Try to navigate to /dashboard/patients",
     "URL: /dashboard/patients", "Access blocked/redirected by ProtectedRoute", "High"),

    # ---------------- Appointments ----------------
    ("Appointments", "View appointments split into Upcoming and Past", "Appointments exist in both the future and the past",
     "1. Navigate to Appointments page",
     "N/A", "Two separate tables: Upcoming Appointments (soonest first) and Past & Closed Appointments (most recent first), each with its own count and pagination", "High"),
    ("Appointments", "Cancelled future appointment is not listed as Upcoming", "A future-dated appointment has been cancelled",
     "1. Cancel a future appointment\n2. Reload the Appointments page",
     "Future date, status Cancelled", "It appears under Past & Closed, NOT under Upcoming (only still-Scheduled future bookings are upcoming)", "Medium"),
    ("Appointments", "Today's appointment with no time stays Upcoming", "An appointment exists for today with the time field empty",
     "1. View the Appointments page",
     "Today's date, no time", "Still listed as Upcoming until the end of today rather than dropping into history", "Low"),
    ("Appointments", "Doctor column shows the current doctor", "An appointment exists whose stored doctor name is blank or outdated",
     "1. View the Appointments page\n2. Check the Doctor column for that appointment",
     "N/A", "The live doctor is resolved from the appointment's doctor reference and shown with specialization; the column is not blank", "High"),
    ("Appointments", "Deleted doctor is flagged on old appointments", "An appointment references a doctor who has since been deleted",
     "1. View the Appointments page",
     "N/A", "The stored name is shown marked 'No longer registered' rather than presented as a current doctor", "Medium"),
    ("Appointments", "Doctor dropdown excludes doctors on leave", "One doctor has status On Leave, others Available/Busy",
     "1. Open New Appointment\n2. Open the Select Doctor dropdown",
     "One doctor set to On Leave", "On Leave doctors are not offered; Available and Busy doctors are (Busy is transient and still bookable for a future date)", "Medium"),
    ("Appointments", "Search the doctor dropdown by specialization", "Doctors with differing specializations exist",
     "1. Open New Appointment\n2. Type a specialization into Select Doctor",
     "e.g. 'General'", "Options are labelled 'Name - Specialization' and filter on the specialization text too", "Low"),
    ("Appointments", "Doctor list fails to load in New Appointment", "Logged in as a role with appointments access but no doctors read access",
     "1. Open New Appointment",
     "N/A", "A clear error message is shown rather than a silently empty doctor dropdown", "Medium"),
    ("Appointments", "Book a new appointment", "Patient and doctor records exist",
     "1. Go to Add Appointment page\n2. Select patient, doctor, date/time\n3. Submit",
     "Existing patient + doctor, future date/time", "Appointment is created; VisitSession auto-opened with Doctor Fee + Center Fee lines", "High"),
    ("Appointments", "Book appointment with a past date/time", "None",
     "1. Go to Add Appointment\n2. Select a date/time in the past\n3. Submit",
     "Past date", "Validation prevents booking a past-dated appointment", "Medium"),
    ("Appointments", "Book overlapping/duplicate appointment for same doctor/slot", "An appointment already exists for that doctor/slot",
     "1. Attempt to book same doctor at an already-booked time slot\n2. Submit",
     "Same doctor, same time slot", "System warns or prevents double-booking for that slot", "Medium"),
    ("Appointments", "Cancel an appointment", "An OPEN appointment exists",
     "1. From Appointments list, select an appointment\n2. Cancel it",
     "N/A", "Appointment status changes to canceled; linked VisitSession reflects CANCELED where applicable", "High"),
    ("Appointments", "Reschedule an appointment", "An existing appointment exists",
     "1. Open an appointment\n2. Change date/time\n3. Save",
     "New valid date/time", "Appointment updates with new schedule, no duplicate created", "Medium"),
    ("Appointments", "Filter appointments by date or doctor", "Multiple appointments exist across dates/doctors",
     "1. Go to Appointments page\n2. Apply date/doctor filter",
     "Specific date or doctor name", "List filters correctly to matching appointments", "Low"),

    # ---------------- Inventory / Pharmacy ----------------
    ("Inventory", "View medicine inventory list", "At least one medicine exists",
     "1. Navigate to Inventory page",
     "N/A", "Medicine list shows name, stock quantity, price, expiry", "High"),
    ("Inventory", "Add a new medicine with valid details", "Logged in with staff role",
     "1. Go to Add Medicine page\n2. Fill name, quantity, price, expiry date\n3. Submit",
     "name: Paracetamol 500mg, qty: 100", "Medicine is added and appears in Inventory list", "High"),
    ("Inventory", "Add medicine with negative or zero stock quantity", "None",
     "1. Go to Add Medicine\n2. Enter negative/zero quantity\n3. Submit",
     "qty: -5", "Validation rejects invalid quantity", "Medium"),
    ("Inventory", "Add medicine with expiry date in the past", "None",
     "1. Go to Add Medicine\n2. Enter a past expiry date\n3. Submit",
     "Expiry: past date", "Validation warns/rejects past expiry date", "Low"),
    ("Inventory", "Edit medicine details / update stock", "Medicine record exists",
     "1. Open Edit Medicine\n2. Update stock quantity or price\n3. Save",
     "Updated qty: 150", "Changes persist and reflect in Inventory list", "High"),
    ("Inventory", "Low stock warning indicator", "A medicine's stock is below threshold",
     "1. Set/observe a medicine with low stock\n2. View Inventory page",
     "Stock below reorder level", "Low-stock medicines are visually flagged/highlighted", "Medium"),
    ("Inventory", "Delete a medicine from inventory", "Medicine record exists, not referenced by pending prescriptions",
     "1. From Inventory list, delete a medicine\n2. Confirm",
     "N/A", "Medicine is removed from list and no longer selectable in prescriptions", "Medium"),

    # ---------------- Pharmacy Dispense Queue ----------------
    ("Pharmacy Dispense Queue", "View queued prescriptions", "A prescription with QUEUED items exists",
     "1. Log in with pharmacy_read (or pharmacy_allow_all)\n2. Go to Pharmacy > Dispensing Queue tab",
     "N/A", "Queued items list shows patient, doctor, medicine, dosage, prescribed/dispensed quantity and status", "High"),
    ("Pharmacy Dispense Queue", "Doctor name shown in the queue is the real author", "A typed prescription exists",
     "1. View the Dispensing Queue\n2. Compare the Doctor column against the doctor who wrote it",
     "N/A", "Doctor shown is the authenticated doctor who saved the prescription, derived server-side (not a client-supplied value)", "Medium"),
    ("Pharmacy Dispense Queue", "Read-only pharmacy user cannot dispense", "Logged in with pharmacy_read but NOT pharmacy_edit",
     "1. Open the Dispensing Queue\n2. Attempt to dispense or reject an item",
     "N/A", "Action is refused by the server with a permission error; no stock movement and no bill line", "High"),
    ("Pharmacy Dispense Queue", "Dispense a prescription with sufficient stock", "QUEUED prescription exists, stock available",
     "1. Open a queued prescription\n2. Click Dispense\n3. Confirm",
     "Medicine with stock >= prescribed qty", "Prescription status changes to DISPENSED, stock decrements, bill line posted to VisitSession atomically", "High"),
    ("Pharmacy Dispense Queue", "Attempt to dispense with insufficient stock", "QUEUED prescription exists, stock less than prescribed qty",
     "1. Open a queued prescription where stock < required qty\n2. Attempt to dispense",
     "Prescribed qty > available stock", "System blocks full dispense or offers PARTIAL fulfillment with clear message", "High"),
    ("Pharmacy Dispense Queue", "Partially dispense a prescription item", "QUEUED item exists, partial stock available",
     "1. Open a queued item\n2. Dispense less than the prescribed quantity",
     "Prescribed 10, dispense 4", "Item becomes PARTIAL; stock decrements by 4 only; one MEDICATION bill line for 4; prescription stays PENDING", "High"),
    ("Pharmacy Dispense Queue", "Partially dispensed item stays in the queue", "An item was partially dispensed",
     "1. After a partial dispense, return to the Dispensing Queue",
     "Prescribed 10, dispensed 4", "The item is STILL listed (outstanding = QUEUED or PARTIAL) and shows the remaining quantity (6 remaining)", "High"),
    ("Pharmacy Dispense Queue", "Dispense the remainder of a partial item", "An item is PARTIAL with quantity still owed",
     "1. Open the PARTIAL item\n2. Confirm the pre-filled quantity",
     "Remaining 6", "Dialog defaults to the REMAINING quantity (6, not 10); dispense succeeds; item becomes DISPENSED; a second MEDICATION bill line is posted", "High"),
    ("Pharmacy Dispense Queue", "Visit does not reach payment while an item is outstanding", "An item is QUEUED or PARTIAL on the visit",
     "1. Partially dispense an item\n2. Check the visit in Billing",
     "Prescribed 10, dispensed 4", "Visit stays at pharmacy and is NOT collectable in Billing until every item on the visit is resolved", "High"),
    ("Pharmacy Dispense Queue", "Reject the remainder of a partial item", "An item is PARTIAL and the rest cannot be supplied",
     "1. Open the PARTIAL item\n2. Reject with a reason",
     "Reason: out of stock", "Remainder is written off, no further stock movement or bill line; the visit can now progress to payment", "Medium"),
    ("Pharmacy Dispense Queue", "Cannot dispense an already completed item", "An item is fully DISPENSED",
     "1. Attempt to dispense the same item again",
     "N/A", "Request is rejected; no extra stock movement and no duplicate bill line", "High"),
    ("Pharmacy Dispense Queue", "Reject a prescription", "QUEUED prescription exists",
     "1. Open queued prescription\n2. Click Reject\n3. Provide reason (if required)\n4. Confirm",
     "N/A", "Prescription status changes to REJECTED; no stock/bill changes occur", "Medium"),
    ("Pharmacy Dispense Queue", "Non-permitted role cannot access Pharmacy page", "Logged in as a role without pharmacy_read / pharmacy_allow_all",
     "1. Log in as a doctor (no pharmacy permission)\n2. Try /dashboard/pharmacy",
     "URL: /dashboard/pharmacy", "Access blocked/redirected by ProtectedRoute, and the API also refuses the underlying requests", "High"),
    ("Pharmacy Dispense Queue", "Concurrent dispensing cannot oversell stock", "One medicine with limited stock; two pharmacy users",
     "1. Set a medicine's stock to 10\n2. Have two users each dispense 7 of it at the same time",
     "Stock 10, two requests of 7", "Exactly one request succeeds; the other is refused for insufficient stock; final stock is 3 and never negative", "High"),

    # ---------------- External / Manual Prescription ----------------
    ("External Prescription", "External Rx is a separate workflow from the queue", "Logged in with pharmacy access",
     "1. Go to Pharmacy\n2. Observe the tabs",
     "N/A", "Two tabs: Dispensing Queue (our doctors' typed prescriptions) and External Rx (paper prescriptions from outside)", "High"),
    ("External Prescription", "Dispense a paper prescription for a registered patient", "Patient registered; medicines in stock",
     "1. Open External Rx\n2. Keep Registered Patient selected and choose the patient\n3. Enter the outside doctor's name\n4. Add medicines and quantities\n5. Click Dispense",
     "Patient + 2 medicines", "Stock decreases for each medicine, MEDICATION bill lines are created, and the charges appear in Billing", "High"),
    ("External Prescription", "Medicines can only be chosen from inventory", "Open External Rx",
     "1. Try to type a medicine name that is not in inventory",
     "Free-text medicine name", "Only inventory medicines are selectable; arbitrary names cannot be entered", "High"),
    ("External Prescription", "Price comes from the current inventory price", "A medicine with a known unit price",
     "1. Add that medicine with a quantity\n2. Compare the line amount and total",
     "qty 3 of a priced medicine", "Unit price and line amount match the current inventory price; the total is the sum of the lines", "Medium"),
    ("External Prescription", "Live stock is shown and shortages flagged", "A medicine with limited stock",
     "1. Select that medicine\n2. Enter a quantity above its stock",
     "qty > stock", "In-stock figure is displayed and the quantity is visibly flagged before submitting", "Medium"),
    ("External Prescription", "Dispensing more than available stock is refused", "A medicine with limited stock",
     "1. Enter a quantity greater than the stock\n2. Click Dispense",
     "qty > available stock", "Refused with a message naming the medicine and the available quantity; NO stock is moved and no bill line is created", "High"),
    ("External Prescription", "A short line rolls back the whole prescription", "Two medicines, the second short of stock",
     "1. Add medicine A with valid quantity and medicine B above its stock\n2. Click Dispense",
     "A: valid, B: qty > stock", "Whole request is refused; medicine A's stock is NOT reduced (all lines commit together or not at all) and no partial record is left", "High"),
    ("External Prescription", "Same medicine listed twice is refused", "Open External Rx",
     "1. Add the same medicine on two separate lines\n2. Click Dispense",
     "Same medicine x2", "Refused with a message to combine the quantities into one line", "Medium"),
    ("External Prescription", "Zero or fractional quantity is refused", "Open External Rx",
     "1. Enter a quantity of 0 or a decimal\n2. Click Dispense",
     "qty: 0 / 2.5", "Refused; quantities must be whole numbers of at least 1", "Medium"),
    ("External Prescription", "External Rx never enters the doctor prescription queue", "An external prescription was dispensed",
     "1. Dispense an external prescription\n2. Open the Dispensing Queue tab",
     "N/A", "Nothing from the external prescription appears in the Dispensing Queue, and no doctor prescription record is fabricated for it", "High"),
    ("External Prescription", "Bill onto the patient's existing open visit", "The patient has an open visit for today",
     "1. Select the registered patient\n2. In Bill to, pick their open visit\n3. Dispense",
     "Existing open visit", "MEDICATION lines are added to that visit alongside the existing fees, and the visit's status is left unchanged", "High"),
    ("External Prescription", "External billing does not disturb the doctor workflow", "The patient has a visit awaiting consultation or pharmacy",
     "1. Bill an external prescription onto that visit\n2. Check the visit's progress",
     "N/A", "The visit continues through the normal consultation/pharmacy flow exactly as before; only the extra charge is added", "High"),
    ("External Prescription", "Standalone pharmacy bill when there is no visit", "The patient has no open visit",
     "1. Select the patient (Bill to = New pharmacy bill)\n2. Dispense",
     "N/A", "A separate pharmacy bill is created containing only medication charges (no doctor or centre fee) and is immediately collectable in Billing", "High"),
    ("External Prescription", "GUEST - dispense to an unregistered walk-in", "Medicines in stock",
     "1. Open External Rx\n2. Switch to Guest (not registered)\n3. Enter the guest's name and optionally a phone\n4. Add medicines\n5. Click Dispense",
     "Guest: Walk-in Visitor, 0770001111", "Sale succeeds, stock decreases, and a pharmacy bill is created for the guest and appears in Billing", "High"),
    ("External Prescription", "GUEST - no patient record is created", "Note the patient count before testing",
     "1. Dispense to a guest\n2. Open the Patients page and re-check the count/list",
     "Guest name", "No new patient record is created; the patient registry and patient counts are unchanged", "High"),
    ("External Prescription", "GUEST - bill is identifiable in Billing", "A guest sale was dispensed",
     "1. Open Billing\n2. Locate the guest's bill",
     "N/A", "The bill is listed under the guest's name marked as a guest, so staff can tell it apart from a registered patient's bill", "Medium"),
    ("External Prescription", "GUEST - name is required", "Guest mode selected",
     "1. Switch to Guest\n2. Leave the name blank (or spaces only)\n3. Click Dispense",
     "Blank / '   '", "Refused asking for either a registered patient or a guest name; nothing is dispensed", "High"),
    ("External Prescription", "GUEST - cannot be billed onto a real patient's visit", "An open visit exists for a registered patient",
     "1. Switch to Guest\n2. Attempt to submit with an existing visit as the bill target",
     "Guest + existing visitSessionId", "Refused; a guest sale can never be charged to another patient's visit", "High"),
    ("External Prescription", "GUEST - no Bill to selector is offered", "Guest mode selected",
     "1. Switch to Guest and review the form",
     "N/A", "The Bill to selector is hidden and the form explains a separate pharmacy bill will be created", "Low"),
    ("External Prescription", "Switching between Registered and Guest clears the other identity", "Open External Rx",
     "1. Select a registered patient\n2. Switch to Guest\n3. Switch back",
     "N/A", "Only the relevant identity fields are used; the submitted sale matches the mode shown on screen", "Medium"),
    ("External Prescription", "PERMISSION - read-only pharmacy user cannot dispense", "Logged in with pharmacy_read but NOT pharmacy_edit",
     "1. Open External Rx\n2. Complete the form and click Dispense",
     "N/A", "Server refuses with a permission error; no stock movement and no bill created (enforced server-side, not just hidden in the UI)", "High"),
    ("External Prescription", "PERMISSION - role without pharmacy access is blocked", "Logged in as a doctor or other non-pharmacy role",
     "1. Attempt to reach /dashboard/pharmacy and to call the external dispense API directly",
     "N/A", "Both the page and the API are refused", "High"),
    ("External Prescription", "PERMISSION - patient and medicine pickers need read access", "Logged in with pharmacy access but without patients read / inventory read",
     "1. Open External Rx",
     "N/A", "A clear message explains which access is missing rather than showing empty dropdowns", "Medium"),
    ("External Prescription", "Dispensed-by is recorded from the logged-in user", "Logged in as a pharmacy user",
     "1. Dispense an external prescription\n2. Inspect the stored record",
     "N/A", "The record shows the authenticated pharmacy user as dispenser; a name supplied in the request body is ignored", "Medium"),
    ("External Prescription", "Concurrent external dispensing cannot oversell", "One medicine with limited stock; two pharmacy users",
     "1. Set stock to 10\n2. Two users each dispense 7 of that medicine simultaneously",
     "Stock 10, two requests of 7", "Exactly one succeeds; the other is refused; final stock is 3 and never negative", "High"),
    ("External Prescription", "Stock figures refresh after dispensing", "An external prescription was just dispensed",
     "1. Dispense, then re-open the medicine picker",
     "N/A", "The in-stock figures reflect the quantities just dispensed", "Low"),

    # ---------------- Billing & Payments ----------------
    ("Billing", "View billing list / visit sessions", "At least one visit session exists",
     "1. Navigate to Billing page",
     "N/A", "List shows patient, visit status (OPEN/PENDING_PHARMACY/READY_FOR_PAYMENT/CLOSED), total amount", "High"),
    ("Billing", "Create invoice for a visit ready for payment", "VisitSession status is READY_FOR_PAYMENT",
     "1. Open Billing for a patient\n2. Click Create Invoice\n3. Review line items (Doctor Fee, Center Fee, Pharmacy)\n4. Confirm",
     "N/A", "Invoice is generated with correct itemized totals matching all posted bill lines", "High"),
    ("Billing", "Attempt to create invoice while pharmacy items are still pending", "VisitSession status is PENDING_PHARMACY",
     "1. Open Billing for a visit still awaiting pharmacy dispense\n2. Attempt to create invoice",
     "N/A", "System prevents invoice creation or clearly flags pending pharmacy items until resolved", "High"),
    ("Billing", "Verify bill line accuracy (Doctor Fee + Center Fee + Pharmacy items)", "Appointment created and prescription dispensed",
     "1. Create appointment (auto Doctor Fee + Center Fee)\n2. Dispense a prescription\n3. Open Billing for that visit",
     "N/A", "All bill lines appear correctly with accurate amounts and no duplication", "High"),
    ("Billing", "Close a visit session after payment", "Invoice created and payment recorded",
     "1. Process payment for an invoice\n2. Verify visit session status",
     "N/A", "VisitSession status transitions to CLOSED; visit no longer editable", "High"),
    ("Payments", "Record a payment against an invoice", "An unpaid invoice exists",
     "1. Navigate to Payments page\n2. Select invoice\n3. Enter payment amount/method\n4. Submit",
     "Full payment amount", "Payment is recorded, invoice marked as paid, reflected in reports", "High"),
    ("Payments", "Record a partial payment", "An unpaid invoice exists",
     "1. Go to Payments\n2. Enter an amount less than total due\n3. Submit",
     "Partial amount", "Payment recorded, remaining balance correctly tracked and displayed", "Medium"),
    ("Payments", "Record payment with amount exceeding invoice total", "An unpaid invoice exists",
     "1. Go to Payments\n2. Enter amount greater than invoice total\n3. Submit",
     "Amount > total due", "System rejects or flags overpayment with a validation message", "Medium"),
    ("Payments", "View payment history for a patient", "Patient has prior payments",
     "1. Navigate to patient's billing/payment history",
     "N/A", "All past payments display with date, amount, method, and reference", "Medium"),

    # ---------------- Reports ----------------
    ("Reports", "Generate daily revenue report", "Billing/payment data exists for the day",
     "1. Navigate to Reports page\n2. Select 'Daily' and today's date\n3. Generate report",
     "Today's date", "Report shows accurate totals matching recorded payments for the day", "High"),
    ("Reports", "Generate report for a custom date range", "Billing data exists within range",
     "1. Go to Reports\n2. Select a custom start/end date\n3. Generate",
     "Start: 2026-08-01, End: 2026-08-16", "Report aggregates correctly across the selected range only", "Medium"),
    ("Reports", "Generate report with no data in selected range", "No transactions in a chosen future range",
     "1. Go to Reports\n2. Select a date range with no activity\n3. Generate",
     "Future date range", "Report shows empty state / zero totals without errors", "Low"),
    ("Reports", "Export report (if supported)", "A report has been generated",
     "1. Generate any report\n2. Click Export/Download",
     "N/A", "Report downloads in expected format (PDF/CSV/Excel) with matching data", "Low"),

    # ---------------- Settings & General/Navigation ----------------
    ("Settings", "View and update profile settings", "Logged in user",
     "1. Navigate to Settings page\n2. Update name/contact/password\n3. Save",
     "Updated display name", "Changes are saved and reflected across the app (e.g. Navbar)", "Medium"),
    ("Settings", "Change password with correct current password", "Logged in user",
     "1. Go to Settings\n2. Enter current password + new password\n3. Save",
     "Valid current password + new password", "Password updated; user can log in with new password", "High"),
    ("Settings", "Change password with incorrect current password", "Logged in user",
     "1. Go to Settings\n2. Enter wrong current password + new password\n3. Save",
     "Wrong current password", "Update rejected with clear error message", "Medium"),
    ("Navigation", "Sidebar shows only permitted menu items per role", "Logged in as various roles",
     "1. Log in as each role (admin, doctor, billing, patient_manager)\n2. Observe Sidebar menu",
     "N/A", "Only menu items the role has permission for are visible", "High"),
    ("Navigation", "Notification bell displays relevant alerts", "System has pending items (e.g. low stock, queued prescriptions)",
     "1. Log in\n2. Click Notification Bell icon",
     "N/A", "Relevant notifications display (e.g. low stock, pending pharmacy items)", "Low"),
    ("Navigation", "Unknown route redirects to login/home", "None",
     "1. Navigate to a non-existent URL (e.g. /dashboard/xyz123)",
     "URL: /dashboard/xyz123", "App redirects to '/' (login) instead of showing a blank/broken page", "Low"),
    ("Navigation", "Responsive layout on smaller screen widths", "None",
     "1. Resize browser to tablet/mobile width\n2. Navigate through dashboard pages",
     "N/A", "Layout adjusts (sidebar collapses/hides) without breaking content", "Low"),
]


def build_workbook():
    wb = Workbook()
    ws = wb.active
    ws.title = "Manual Test Cases"

    header_fill = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF", size=11)
    wrap_align = Alignment(wrap_text=True, vertical="top", horizontal="left")
    center_align = Alignment(wrap_text=True, vertical="top", horizontal="center")
    thin_border = Border(
        left=Side(style="thin", color="D9D9D9"),
        right=Side(style="thin", color="D9D9D9"),
        top=Side(style="thin", color="D9D9D9"),
        bottom=Side(style="thin", color="D9D9D9"),
    )

    ws.append(COLUMNS)
    for col_idx in range(1, len(COLUMNS) + 1):
        cell = ws.cell(row=1, column=col_idx)
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = center_align
        cell.border = thin_border

    module_counters = {}
    row_idx = 2
    for module, scenario, precond, steps, data, expected, priority in TEST_CASES:
        prefix = "".join(w[0] for w in module.split()).upper()
        module_counters[prefix] = module_counters.get(prefix, 0) + 1
        tc_id = f"TC-{prefix}-{module_counters[prefix]:03d}"

        row = [tc_id, module, scenario, precond, steps, data, expected, "", "Not Executed", priority, "", "", ""]
        ws.append(row)
        for col_idx in range(1, len(COLUMNS) + 1):
            cell = ws.cell(row=row_idx, column=col_idx)
            cell.border = thin_border
            cell.alignment = wrap_align
        row_idx += 1

    last_row = row_idx - 1

    # Column widths
    widths = {
        "A": 14, "B": 22, "C": 34, "D": 26, "E": 40, "F": 24,
        "G": 42, "H": 22, "I": 16, "J": 10, "K": 14, "L": 14, "M": 24,
    }
    for col, width in widths.items():
        ws.column_dimensions[col].width = width

    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:{get_column_letter(len(COLUMNS))}{last_row}"

    # Data validation dropdowns for Status and Priority
    status_dv = DataValidation(
        type="list", formula1='"Pass,Fail,Blocked,Not Executed"', allow_blank=True
    )
    ws.add_data_validation(status_dv)
    status_dv.add(f"I2:I{last_row}")

    priority_dv = DataValidation(
        type="list", formula1='"High,Medium,Low"', allow_blank=True
    )
    ws.add_data_validation(priority_dv)
    priority_dv.add(f"J2:J{last_row}")

    # Conditional-ish manual coloring hint row height
    for r in range(2, last_row + 1):
        ws.row_dimensions[r].height = 60

    wb.save(OUTPUT_PATH)
    print(f"Wrote {last_row - 1} test cases to {OUTPUT_PATH}")


if __name__ == "__main__":
    build_workbook()
