export const SPECIALIZATIONS = [
  "General Medicine",
  "Cardiology",
  "Neurology",
  "Pediatrics",
  "Orthopedics",
  "Dermatology",
  "Gynecology & Obstetrics",
  "Psychiatry",
  "ENT (Ear, Nose & Throat)",
  "Ophthalmology",
  "Urology",
  "Gastroenterology",
  "Endocrinology",
  "Nephrology",
  "Pulmonology",
  "Oncology",
  "Rheumatology",
  "General Surgery",
  "Dentistry",
  "Radiology",
];
